/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "calculator_types.h"

#include "calculator_types.tcc"

#include <algorithm>

namespace example { namespace cpp2 {

}} // example::cpp2