/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "calculator_types.h"
#include <thrift/lib/cpp2/protocol/Protocol.h>
namespace example { namespace cpp2 {

class calculatorConstants {
 public:
  calculatorConstants() {}
};

extern const calculatorConstants g_calculator_constants;

}} // example::cpp2