/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "calculator_constants.h"

namespace example { namespace cpp2 {

const calculatorConstants __attribute__((__deprecated__("g_calculator_constants suffers from the 'static initialization order fiasco' (https://isocpp.org/wiki/faq/ctors#static-init-order) and may CRASH you program. Instead, use calculator_constants::CONSTANT_NAME"))) g_calculator_constants;

}} // example::cpp2