/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Calculator.h"

#include "Calculator.tcc"

namespace example { namespace cpp2 {

}} // example::cpp2
namespace apache { namespace thrift {

}} // apache::thrift